package gt.edu.umg.proyectodos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author fuent
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /**
     * @return true;
     * valida que los campos no esten vacion o con estacios
     */
    private boolean validarCampos() {
        if (txtNombre.getText() == null || txtNombre.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Nombre' está vacío o contiene solo espacios.");
            return false;
        }
        if (txtApellido.getText() == null || txtApellido.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Apellido' está vacío o contiene solo espacios.");
            return false;
        }
        if (txtasignatura1.getText() == null || txtasignatura1.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Asignatura 1' está vacío o contiene solo espacios.");
            return false;
        }
        if (txtasignatura2.getText() == null || txtasignatura2.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Asignatura 2' está vacío o contiene solo espacios.");
            return false;
        }
        if (txtasignatura3.getText() == null || txtasignatura3.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Asignatura 3' está vacío o contiene solo espacios.");
            return false;
        }
        if (txtasignatura4.getText() == null || txtasignatura4.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Asignatura 4' está vacío o contiene solo espacios.");
            return false;
        }
        if (txtasignatura5.getText() == null || txtasignatura5.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Asignatura 5' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta1b1.getText() == null || txta1b1.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Primer Bimestre Asignatura 1' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta2b1.getText() == null || txta2b1.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Primer Bimestre Asignatura 2' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta3b1.getText() == null || txta3b1.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Primer Bimestre Asignatura 3' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta4b1.getText() == null || txta4b1.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Primer Bimestre Asignatura 4' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta5b1.getText() == null || txta5b1.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Primer Bimestre Asignatura 5' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta1b2.getText() == null || txta1b2.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Segundo Bimestre Asignatura 1' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta2b2.getText() == null || txta2b2.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Segundo Bimestre Asignatura 2' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta3b2.getText() == null || txta3b2.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Segundo Bimestre Asignatura 3' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta4b2.getText() == null || txta4b2.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Segundo Bimestre Asignatura 4' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta5b2.getText() == null || txta5b2.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Segundo Bimestre Asignatura 5' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta1b3.getText() == null || txta1b3.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Tercer Bimestre Asignatura 1' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta2b3.getText() == null || txta2b3.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Tercer Bimestre Asignatura 2' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta3b3.getText() == null || txta3b3.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Tercer Bimestre Asignatura 3' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta4b3.getText() == null || txta4b3.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Tercer Bimestre Asignatura 4' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta5b3.getText() == null || txta5b3.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Tercer Bimestre Asignatura 5' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta1b4.getText() == null || txta1b4.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Cuarto Bimestre Asignatura 1' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta2b4.getText() == null || txta2b4.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Cuarto Bimestre Asignatura 2' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta3b4.getText() == null || txta3b4.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Cuarto Bimestre Asignatura 3' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta4b4.getText() == null || txta4b4.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Cuarto Bimestre Asignatura 4' está vacío o contiene solo espacios.");
            return false;
        }
        if (txta5b4.getText() == null || txta5b4.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo 'Cuarto Bimestre Asignatura 5' está vacío o contiene solo espacios.");
            return false;
        }

        

        return true;
    }

    /**
     * @param indice recibe el indice que tiene la base de datos alumno y es que
     * el guia para relacionar cada alumno con su materia y notas (PRIMARYKEY)
     */
    private void cargarDatos(int indice) {
        try (Connection con = DBConnection.getConnection()) {
            String query = "SELECT * FROM Alumno "
                    + "INNER JOIN Notas ON Alumno.Id_Alumno = Notas.id_Alumno "
                    + "INNER JOIN Materia ON Notas.id_Materia = Materia.Id_Materia "
                    + "WHERE Alumno.Id_Alumno = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, indice);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Carga los datos del alumno
                txtNombre.setText(rs.getString("Nombre"));
                txtApellido.setText(rs.getString("Apellido"));

                //notas y materias
                int i = 1;
                do {
                    switch (i) {
                        case 1 -> {
                            txtasignatura1.setText(rs.getString("Materia"));
                            txta1b1.setText(String.valueOf(rs.getDouble("PrimerBimestre")));
                            txta1b2.setText(String.valueOf(rs.getDouble("SegundoBimestre")));
                            txta1b3.setText(String.valueOf(rs.getDouble("TercerBimestre")));
                            txta1b4.setText(String.valueOf(rs.getDouble("CuartoBimestre")));
                            txtpromedio1.setText(String.valueOf(rs.getDouble("PromedioFinal")));
                        }
                        case 2 -> {
                            txtasignatura2.setText(rs.getString("Materia"));
                            txta2b1.setText(String.valueOf(rs.getDouble("PrimerBimestre")));
                            txta2b2.setText(String.valueOf(rs.getDouble("SegundoBimestre")));
                            txta2b3.setText(String.valueOf(rs.getDouble("TercerBimestre")));
                            txta2b4.setText(String.valueOf(rs.getDouble("CuartoBimestre")));
                            txtpromedio2.setText(String.valueOf(rs.getDouble("PromedioFinal")));
                        }
                        case 3 -> {
                            txtasignatura3.setText(rs.getString("Materia"));
                            txta3b1.setText(String.valueOf(rs.getDouble("PrimerBimestre")));
                            txta3b2.setText(String.valueOf(rs.getDouble("SegundoBimestre")));
                            txta3b3.setText(String.valueOf(rs.getDouble("TercerBimestre")));
                            txta3b4.setText(String.valueOf(rs.getDouble("CuartoBimestre")));
                            txtpromedio3.setText(String.valueOf(rs.getDouble("PromedioFinal")));
                        }
                        case 4 -> {
                            txtasignatura4.setText(rs.getString("Materia"));
                            txta4b1.setText(String.valueOf(rs.getDouble("PrimerBimestre")));
                            txta4b2.setText(String.valueOf(rs.getDouble("SegundoBimestre")));
                            txta4b3.setText(String.valueOf(rs.getDouble("TercerBimestre")));
                            txta4b4.setText(String.valueOf(rs.getDouble("CuartoBimestre")));
                            txtpromedio4.setText(String.valueOf(rs.getDouble("PromedioFinal")));
                        }
                        case 5 -> {
                            txtasignatura5.setText(rs.getString("Materia"));
                            txta5b1.setText(String.valueOf(rs.getDouble("PrimerBimestre")));
                            txta5b2.setText(String.valueOf(rs.getDouble("SegundoBimestre")));
                            txta5b3.setText(String.valueOf(rs.getDouble("TercerBimestre")));
                            txta5b4.setText(String.valueOf(rs.getDouble("CuartoBimestre")));
                            txtpromedio5.setText(String.valueOf(rs.getDouble("PromedioFinal")));
                        }
                        default -> {
                        }
                    }

                    i++;
                } while (rs.next() && i < 6);
            }
        } catch (SQLException e) {
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtasignatura1 = new javax.swing.JTextField();
        txtasignatura2 = new javax.swing.JTextField();
        txtasignatura3 = new javax.swing.JTextField();
        txtasignatura4 = new javax.swing.JTextField();
        txtasignatura5 = new javax.swing.JTextField();
        txta1b1 = new javax.swing.JTextField();
        txta2b1 = new javax.swing.JTextField();
        txta3b1 = new javax.swing.JTextField();
        txta4b1 = new javax.swing.JTextField();
        txta5b1 = new javax.swing.JTextField();
        txta1b2 = new javax.swing.JTextField();
        txta2b2 = new javax.swing.JTextField();
        txta3b2 = new javax.swing.JTextField();
        txta4b2 = new javax.swing.JTextField();
        txta5b2 = new javax.swing.JTextField();
        txta5b3 = new javax.swing.JTextField();
        txta4b3 = new javax.swing.JTextField();
        txta3b3 = new javax.swing.JTextField();
        txta2b3 = new javax.swing.JTextField();
        txta1b3 = new javax.swing.JTextField();
        txta1b4 = new javax.swing.JTextField();
        txta2b4 = new javax.swing.JTextField();
        txta3b4 = new javax.swing.JTextField();
        txta4b4 = new javax.swing.JTextField();
        txta5b4 = new javax.swing.JTextField();
        txtpromedio1 = new javax.swing.JTextField();
        txtpromedio2 = new javax.swing.JTextField();
        txtpromedio3 = new javax.swing.JTextField();
        txtpromedio4 = new javax.swing.JTextField();
        txtpromedio5 = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        txtIndice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(168, 187, 199));
        jPanel1.setForeground(new java.awt.Color(189, 189, 170));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel1.setText("Segundo Primaria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Asignatura");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Bloques");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("3");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("4");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Promedio");

        txtasignatura1.setBackground(new java.awt.Color(250, 236, 223));

        txtasignatura2.setBackground(new java.awt.Color(250, 236, 223));

        txtasignatura3.setBackground(new java.awt.Color(250, 236, 223));

        txtasignatura4.setBackground(new java.awt.Color(250, 236, 223));

        txtasignatura5.setBackground(new java.awt.Color(250, 236, 223));

        txta1b1.setBackground(new java.awt.Color(250, 236, 223));
        txta1b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta1b1ActionPerformed(evt);
            }
        });

        txta2b1.setBackground(new java.awt.Color(250, 236, 223));

        txta3b1.setBackground(new java.awt.Color(250, 236, 223));

        txta4b1.setBackground(new java.awt.Color(250, 236, 223));

        txta5b1.setBackground(new java.awt.Color(250, 236, 223));

        txta1b2.setBackground(new java.awt.Color(250, 236, 223));

        txta2b2.setBackground(new java.awt.Color(250, 236, 223));

        txta3b2.setBackground(new java.awt.Color(250, 236, 223));

        txta4b2.setBackground(new java.awt.Color(250, 236, 223));

        txta5b2.setBackground(new java.awt.Color(250, 236, 223));

        txta5b3.setBackground(new java.awt.Color(250, 236, 223));

        txta4b3.setBackground(new java.awt.Color(250, 236, 223));

        txta3b3.setBackground(new java.awt.Color(250, 236, 223));

        txta2b3.setBackground(new java.awt.Color(250, 236, 223));

        txta1b3.setBackground(new java.awt.Color(250, 236, 223));

        txta1b4.setBackground(new java.awt.Color(250, 236, 223));

        txta2b4.setBackground(new java.awt.Color(250, 236, 223));

        txta3b4.setBackground(new java.awt.Color(250, 236, 223));

        txta4b4.setBackground(new java.awt.Color(250, 236, 223));

        txta5b4.setBackground(new java.awt.Color(250, 236, 223));

        txtpromedio1.setBackground(new java.awt.Color(250, 236, 223));

        txtpromedio2.setBackground(new java.awt.Color(250, 236, 223));

        txtpromedio3.setBackground(new java.awt.Color(250, 236, 223));

        txtpromedio4.setBackground(new java.awt.Color(250, 236, 223));

        txtpromedio5.setBackground(new java.awt.Color(250, 236, 223));

        btnAtras.setBackground(new java.awt.Color(207, 188, 163));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setText("<<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(207, 188, 163));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSiguiente.setText(">>");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(207, 188, 163));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(207, 188, 163));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(207, 188, 163));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalcular.setText("Calcular promedio");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtIndice.setEditable(false);
        txtIndice.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtIndice.setText("1");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Apellido");

        txtNombre.setBackground(new java.awt.Color(250, 236, 223));

        txtApellido.setBackground(new java.awt.Color(250, 236, 223));

        txtEstado.setBackground(new java.awt.Color(250, 236, 223));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(232, 232, 232)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                                .addComponent(jSeparator2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addGap(49, 49, 49)
                                .addComponent(btnCalcular)
                                .addGap(30, 30, 30)
                                .addComponent(btnGuardar)
                                .addGap(37, 37, 37)
                                .addComponent(btnLimpiar)
                                .addGap(43, 43, 43)
                                .addComponent(btnSiguiente))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtasignatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtasignatura2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtasignatura3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtasignatura4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtasignatura5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(49, 49, 49)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(122, 122, 122)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txta2b1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta3b1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta4b1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta5b1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txta2b2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta1b2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta3b2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta4b2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta5b2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txta2b3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta1b3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta3b3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta4b3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta5b3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txta2b4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta1b4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta3b4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta4b4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txta5b4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(txtApellido))))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpromedio1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtpromedio3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpromedio4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpromedio5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpromedio2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstado))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txta1b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta2b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta3b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta4b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta5b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtasignatura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta1b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtasignatura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta2b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtasignatura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta3b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtasignatura4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta4b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtasignatura5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta5b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txta1b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta2b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta3b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta4b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta5b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txta1b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpromedio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txta2b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpromedio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txta3b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpromedio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txta4b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpromedio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txta5b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpromedio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCalcular)
                    .addComponent(btnSiguiente))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txta1b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta1b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txta1b1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        int indice = Integer.parseInt(txtIndice.getText());
        if (indice > 1) {
            indice--;
            cargarDatos(indice);
            txtIndice.setText(String.valueOf(indice));
        }
        Double nota1 = Double.valueOf((txtpromedio1.getText()));
        Double nota2 = Double.valueOf((txtpromedio2.getText()));
        Double nota3 = Double.valueOf((txtpromedio3.getText()));
        Double nota4 = Double.valueOf((txtpromedio4.getText()));
        Double nota5 = Double.valueOf((txtpromedio5.getText()));

        Double sumatoria = nota1 + nota2 + nota3 + nota4 + nota5;
        if (sumatoria < 305) {
            txtEstado.setText("Desaprobado");
        } else {
            txtEstado.setText("Aprobado");
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        int indice = Integer.parseInt(txtIndice.getText());
        indice++;
        cargarDatos(indice);
        txtIndice.setText(String.valueOf(indice));
        Double nota1 = Double.valueOf((txtpromedio1.getText()));
        Double nota2 = Double.valueOf((txtpromedio2.getText()));
        Double nota3 = Double.valueOf((txtpromedio3.getText()));
        Double nota4 = Double.valueOf((txtpromedio4.getText()));
        Double nota5 = Double.valueOf((txtpromedio5.getText()));
        Double sumatoria = nota1 + nota2 + nota3 + nota4 + nota5;
        if (sumatoria < 305) {
            txtEstado.setText("Desaprobado");
        } else {
            txtEstado.setText("Aprobado");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validarCampos()) {
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();

            String[] asignaturas = new String[5];
            asignaturas[0] = txtasignatura1.getText();
            asignaturas[1] = txtasignatura2.getText();
            asignaturas[2] = txtasignatura3.getText();
            asignaturas[3] = txtasignatura4.getText();
            asignaturas[4] = txtasignatura5.getText();

            double[][] notas = new double[5][4];
            notas[0][0] = Double.parseDouble(txta1b1.getText());
            notas[0][1] = Double.parseDouble(txta1b2.getText());
            notas[0][2] = Double.parseDouble(txta1b3.getText());
            notas[0][3] = Double.parseDouble(txta1b4.getText());

            notas[1][0] = Double.parseDouble(txta2b1.getText());
            notas[1][1] = Double.parseDouble(txta2b2.getText());
            notas[1][2] = Double.parseDouble(txta2b3.getText());
            notas[1][3] = Double.parseDouble(txta2b4.getText());

            notas[2][0] = Double.parseDouble(txta3b1.getText());
            notas[2][1] = Double.parseDouble(txta3b2.getText());
            notas[2][2] = Double.parseDouble(txta3b3.getText());
            notas[2][3] = Double.parseDouble(txta3b4.getText());

            notas[3][0] = Double.parseDouble(txta4b1.getText());
            notas[3][1] = Double.parseDouble(txta4b2.getText());
            notas[3][2] = Double.parseDouble(txta4b3.getText());
            notas[3][3] = Double.parseDouble(txta4b4.getText());

            notas[4][0] = Double.parseDouble(txta5b1.getText());
            notas[4][1] = Double.parseDouble(txta5b2.getText());
            notas[4][2] = Double.parseDouble(txta5b3.getText());
            notas[4][3] = Double.parseDouble(txta5b4.getText());

            double[] promedios = new double[5];
            promedios[0] = Double.parseDouble(txtpromedio1.getText());
            promedios[1] = Double.parseDouble(txtpromedio2.getText());
            promedios[2] = Double.parseDouble(txtpromedio3.getText());
            promedios[3] = Double.parseDouble(txtpromedio4.getText());
            promedios[4] = Double.parseDouble(txtpromedio5.getText());

            try (Connection con = DBConnection.getConnection()) {
                String insertAlumno = "INSERT INTO Alumno (Nombre, Apellido) VALUES (?, ?)";
                PreparedStatement psAlumno = con.prepareStatement(insertAlumno, PreparedStatement.RETURN_GENERATED_KEYS);
                psAlumno.setString(1, nombre);
                psAlumno.setString(2, apellido);
                psAlumno.executeUpdate();

                ResultSet rsAlumno = psAlumno.getGeneratedKeys();
                int idAlumno = 0;
                if (rsAlumno.next()) {
                    idAlumno = rsAlumno.getInt(1);
                }

                for (int i = 0; i < asignaturas.length; i++) {

                    String selectMateria = "SELECT Id_Materia FROM Materia WHERE Materia = ?";
                    PreparedStatement psMateriaSelect = con.prepareStatement(selectMateria);
                    psMateriaSelect.setString(1, asignaturas[i]);
                    ResultSet rsMateria = psMateriaSelect.executeQuery();

                    int idMateria = 0;
                    if (rsMateria.next()) {
                        idMateria = rsMateria.getInt("Id_Materia");  // Si la materia ya existe
                    } else {

                        String insertMateria = "INSERT INTO Materia (Materia) VALUES (?)";
                        PreparedStatement psMateriaInsert = con.prepareStatement(insertMateria, PreparedStatement.RETURN_GENERATED_KEYS);
                        psMateriaInsert.setString(1, asignaturas[i]);
                        psMateriaInsert.executeUpdate();

                        ResultSet rsMateriaInsert = psMateriaInsert.getGeneratedKeys();
                        if (rsMateriaInsert.next()) {
                            idMateria = rsMateriaInsert.getInt(1);
                        }
                    }

                    String insertNotas = "INSERT INTO Notas (id_Alumno, id_Materia, PrimerBimestre, SegundoBimestre, TercerBimestre, CuartoBimestre) VALUES (?, ?, ?, ?, ?, ?)";
                    PreparedStatement psNotas = con.prepareStatement(insertNotas);
                    psNotas.setInt(1, idAlumno);
                    psNotas.setInt(2, idMateria);
                    psNotas.setDouble(3, notas[i][0]);
                    psNotas.setDouble(4, notas[i][1]);
                    psNotas.setDouble(5, notas[i][2]);
                    psNotas.setDouble(6, notas[i][3]);
                    psNotas.setDouble(7, promedios[i]);
                    psNotas.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Alumno Guardado");
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (validarCampos()) {
            double[] promedios = new double[5];

            double[][] notas = new double[5][4];
            //bimestres columna dos
            notas[0][0] = Double.parseDouble(txta1b1.getText());  
            notas[0][1] = Double.parseDouble(txta1b2.getText());  
            notas[0][2] = Double.parseDouble(txta1b3.getText());  
            notas[0][3] = Double.parseDouble(txta1b4.getText()); 
            //Asignaturas:
            notas[1][0] = Double.parseDouble(txta2b1.getText());
            notas[1][1] = Double.parseDouble(txta2b2.getText());
            notas[1][2] = Double.parseDouble(txta2b3.getText());
            notas[1][3] = Double.parseDouble(txta2b4.getText());

            notas[2][0] = Double.parseDouble(txta3b1.getText());
            notas[2][1] = Double.parseDouble(txta3b2.getText());
            notas[2][2] = Double.parseDouble(txta3b3.getText());
            notas[2][3] = Double.parseDouble(txta3b4.getText());

            notas[3][0] = Double.parseDouble(txta4b1.getText());
            notas[3][1] = Double.parseDouble(txta4b2.getText());
            notas[3][2] = Double.parseDouble(txta4b3.getText());
            notas[3][3] = Double.parseDouble(txta4b4.getText());

            notas[4][0] = Double.parseDouble(txta5b1.getText());
            notas[4][1] = Double.parseDouble(txta5b2.getText());
            notas[4][2] = Double.parseDouble(txta5b3.getText());
            notas[4][3] = Double.parseDouble(txta5b4.getText());

            for (int i = 0; i < 5; i++) {
                promedios[i] = (notas[i][0] + notas[i][1] + notas[i][2] + notas[i][3]) / 4.0;

                switch (i) {
                    case 0 ->
                        txtpromedio1.setText(String.valueOf(promedios[i]));
                    case 1 ->
                        txtpromedio2.setText(String.valueOf(promedios[i]));
                    case 2 ->
                        txtpromedio3.setText(String.valueOf(promedios[i]));
                    case 3 ->
                        txtpromedio4.setText(String.valueOf(promedios[i]));
                    case 4 ->
                        txtpromedio5.setText(String.valueOf(promedios[i]));
                }
            }

        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtpromedio5.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtasignatura1.setText("");
        txtasignatura2.setText("");
        txtasignatura3.setText("");
        txtasignatura4.setText("");
        txtasignatura5.setText("");
        txta1b1.setText("");
        txta2b1.setText("");
        txta3b1.setText("");
        txta4b1.setText("");
        txta5b1.setText("");
        txta1b2.setText("");
        txta2b2.setText("");
        txta3b2.setText("");
        txta4b2.setText("");
        txta5b2.setText("");
        txta1b3.setText("");
        txta2b3.setText("");
        txta3b3.setText("");
        txta4b3.setText("");
        txta5b3.setText("");
        txta1b4.setText("");
        txta2b4.setText("");
        txta3b4.setText("");
        txta4b4.setText("");
        txta5b4.setText("");
        txtpromedio1.setText("");
        txtpromedio2.setText("");
        txtpromedio3.setText("");
        txtpromedio4.setText("");
        txtpromedio5.setText("");
        txtEstado.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txta1b1;
    private javax.swing.JTextField txta1b2;
    private javax.swing.JTextField txta1b3;
    private javax.swing.JTextField txta1b4;
    private javax.swing.JTextField txta2b1;
    private javax.swing.JTextField txta2b2;
    private javax.swing.JTextField txta2b3;
    private javax.swing.JTextField txta2b4;
    private javax.swing.JTextField txta3b1;
    private javax.swing.JTextField txta3b2;
    private javax.swing.JTextField txta3b3;
    private javax.swing.JTextField txta3b4;
    private javax.swing.JTextField txta4b1;
    private javax.swing.JTextField txta4b2;
    private javax.swing.JTextField txta4b3;
    private javax.swing.JTextField txta4b4;
    private javax.swing.JTextField txta5b1;
    private javax.swing.JTextField txta5b2;
    private javax.swing.JTextField txta5b3;
    private javax.swing.JTextField txta5b4;
    private javax.swing.JTextField txtasignatura1;
    private javax.swing.JTextField txtasignatura2;
    private javax.swing.JTextField txtasignatura3;
    private javax.swing.JTextField txtasignatura4;
    private javax.swing.JTextField txtasignatura5;
    private javax.swing.JTextField txtpromedio1;
    private javax.swing.JTextField txtpromedio2;
    private javax.swing.JTextField txtpromedio3;
    private javax.swing.JTextField txtpromedio4;
    private javax.swing.JTextField txtpromedio5;
    // End of variables declaration//GEN-END:variables
}
